# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0032_auto_20170816_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststat',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='customUser.Commentaire'),
        ),
    ]
