# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-16 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0033_auto_20170816_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketlist',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='status',
            name='owner',
        ),
        migrations.AlterField(
            model_name='poststat',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='poststat',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Bucketlist',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
