# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-19 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0042_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='notified',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='read_by_all',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='unread_by',
        ),
        migrations.AddField(
            model_name='conversation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
