# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0065_auto_20170827_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep_courses', to='customUser.Department'),
        ),
    ]
