# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-30 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0066_auto_20170827_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='classe',
        ),
        migrations.AddField(
            model_name='schedule',
            name='departement',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dep_schedules', to='customUser.Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_schedules', to='customUser.School'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep_students', to='customUser.Department'),
        ),
    ]
