# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-26 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0076_auto_20170926_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pending',
            old_name='Department',
            new_name='department',
        ),
    ]
