# Generated by Django 2.0.1 on 2018-02-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0108_auto_20180128_0020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Other_docs',
            new_name='OtherDocs',
        ),
    ]
