# Generated by Django 2.0.1 on 2018-11-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0114_auto_20181126_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='year',
            field=models.IntegerField(default=3, unique=True),
            preserve_default=False,
        ),
    ]
