# Generated by Django 2.0.1 on 2018-11-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0115_classe_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AlterField(
            model_name='classe',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
