# Generated by Django 2.0.1 on 2018-12-03 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0126_auto_20181129_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryevent',
            name='creator',
        ),
        migrations.AddField(
            model_name='category',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CategoryEvent', to='customUser.Category'),
        ),
        migrations.DeleteModel(
            name='CategoryEvent',
        ),
    ]
