# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-14 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0004_auto_20170810_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fld',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
