# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-14 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0005_user_fld'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fld',
        ),
    ]
