# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-14 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0009_auto_20170814_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='who_is_followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='who_follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
