# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0014_auto_20170815_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='customUser.Comment'),
        ),
    ]
