# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0017_auto_20170815_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='status',
            name='likes',
        ),
    ]
