# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0018_auto_20170815_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='status',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='status',
            name='description',
        ),
        migrations.RemoveField(
            model_name='status',
            name='name',
        ),
    ]
