# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 23:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0030_auto_20170816_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='status',
            name='likes',
        ),
        migrations.AddField(
            model_name='poststat',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='customUser.Comment'),
        ),
        migrations.AddField(
            model_name='poststat',
            name='description',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poststat',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
