# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-16 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0034_auto_20170816_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststat',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='poststat',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
