# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0038_auto_20170818_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='Description',
            new_name='description',
        ),
    ]
