# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0039_auto_20170818_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='belongsTo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='customUser.School'),
        ),
    ]
