# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0040_auto_20170818_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='belongsTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='customUser.School'),
        ),
    ]
