# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-19 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0041_auto_20170818_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_by_all', models.DateTimeField(auto_now_add=True, verbose_name='Read by all')),
                ('notified', models.ManyToManyField(blank=True, related_name='notified_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Notified')),
                ('unread_by', models.ManyToManyField(blank=True, related_name='unread_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Unread by')),
                ('users', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=6255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('convertsation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='customUser.Conversation', verbose_name='Conversation')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
