# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-19 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0043_auto_20170819_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='convertsation',
            new_name='conversation',
        ),
    ]
