# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-21 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0048_message_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_quategory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('picture_url', models.CharField(blank=True, max_length=200)),
                ('is_picture', models.BooleanField(default=False)),
                ('date_beg', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField(auto_now_add=True)),
                ('Participants', models.ManyToManyField(blank=True, related_name='event', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModifSuggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('picture_url', models.CharField(blank=True, max_length=200)),
                ('is_picture', models.BooleanField(default=False)),
                ('SentTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='customUser.School')),
            ],
        ),
        migrations.RemoveField(
            model_name='poststat',
            name='text',
        ),
        migrations.AddField(
            model_name='poststat',
            name='is_picture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poststat',
            name='picture_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='poststat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='SentTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='customUser.School'),
        ),
        migrations.AddField(
            model_name='poststat',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='customUser.Category'),
            preserve_default=False,
        ),
    ]
