# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-22 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0049_auto_20170821_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_category', to=settings.AUTH_USER_MODEL),
        ),
    ]
