# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-23 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0051_auto_20170822_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='belongsTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='customUser.School'),
        ),
    ]
