# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-26 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0057_auto_20170825_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(max_length=255)),
                ('classe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='customUser.Classe')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='customUser.School')),
            ],
        ),
    ]
