# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-26 12:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0059_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerr', to=settings.AUTH_USER_MODEL),
        ),
    ]
