# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-26 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0060_auto_20170826_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='owner',
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
