# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-27 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0063_auto_20170826_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='file_path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
