# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-07 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0069_auto_20170907_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poststat',
            name='is_liked',
        ),
    ]
