# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-26 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0075_user_is_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='pending',
            name='sender',
        ),
        migrations.AddField(
            model_name='pending',
            name='Department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='dep', to='customUser.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pending',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe', to='customUser.Classe'),
        ),
        migrations.AddField(
            model_name='pending',
            name='is_professor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pending',
            name='message',
            field=models.TextField(blank=True, max_length=6255),
        ),
        migrations.AddField(
            model_name='pending',
            name='school',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pendings', to='customUser.School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pending',
            name='user',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
