# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-27 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0077_auto_20170926_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='message',
            field=models.TextField(blank=True, max_length=6255, null=True),
        ),
    ]
