# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-03 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0083_auto_20171003_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
    ]
