# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-03 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0085_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Participants',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
