# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-03 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0088_auto_20171003_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Participants',
            new_name='participants',
        ),
    ]
