# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-15 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0098_auto_20171015_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='%m-%d-%Y'),
        ),
    ]
