# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-15 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0100_auto_20171015_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_social',
            field=models.BooleanField(default=True),
        ),
    ]
