# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-19 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0101_user_first_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
