# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-02 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0105_notification_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='seen',
        ),
    ]
