# Generated by Django 2.0.1 on 2018-11-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0120_remove_classe_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
