# Generated by Django 2.0.1 on 2018-11-27 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0121_classe_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='belongsTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='customUser.Classe'),
        ),
    ]
