# Generated by Django 2.0.1 on 2018-11-27 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0122_user_belongsto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='belongsTo',
        ),
    ]
