# Generated by Django 2.0.1 on 2018-12-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0127_auto_20181203_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='xCoord',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='yCoord',
            new_name='lng',
        ),
    ]
