# Generated by Django 2.0.1 on 2018-12-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0128_auto_20181212_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=10255),
        ),
    ]
