# Generated by Django 2.0.1 on 2018-12-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0129_auto_20181213_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=10255),
        ),
        migrations.AlterField(
            model_name='poststat',
            name='description',
            field=models.CharField(blank=True, max_length=10255),
        ),
    ]
